FLASK_APP=src
FLASK_ENV=development
AUTH0_DOMAIN='agyx.auth0.com'
ALGORITHMS = ['RS256']
API_AUDIENCE = 'http://localhost:5000/'
DATABASE_NAME = 'flat-tutorials'
TEST_DATABASE_NAME = 'flat-tutorials-test'
DATABASE_USER = 'postgres'
DATABASE_LOCATION = 'localhost:5432'
SECRET_KEY = 'vgT0?(XKnWvJfmnRW/:e'
