"""empty message

Revision ID: d6bb7ce4cb39
Revises: 7aa2d6b73335
Create Date: 2020-10-14 00:53:47.164658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bb7ce4cb39'
down_revision = '7aa2d6b73335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unpublished_tutorials', sa.Column('reviewer_notes', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unpublished_tutorials', 'reviewer_notes')
    # ### end Alembic commands ###
